lacabra/proco-map-app

.gitignore, pages/api/getLocationsTest.js, pages/start-test.js, pages/summary.js, pages/test.js
In the production environment a new warning appeared that caused the deployment to fail, namely:
```
│ WARN! It is not possible to use `api` and `pages/api` at the same time, please only use one option │
```
This was a known issue, but hadn't posed problems until now. Thus the code has been refactored to move `api/quizQuestions.js` to `pages/api/getLocationsTest.js`
=> Fix api endpoints

scripts/csvToJson.js
Before we are able to merge #18, the production database needs to be modified to incorporate the field `country_codes` in the table `locations` defined [here](https://github.com/lacabra/proco-map-app/blob/b7f707468840cb1cbe7977b4e3a9997bfeb49547/db/dbOps.js#L44).
This PR modifies the existing script used to convert the school location data received in CSV format into JSON, which later can be used to populate the database. The modification includes parsing the `country` name field into its corresponding `country_code` building on the changes introduced in #15
=> BLD: added parsing of countries

pages/api/saveUserUuid.js
Fix #28.
Previous `then`-block did not resolve the response properly.
Switched to try/catch with async used in many other route handlers.
After testing can confirm that the `API resolved without sending a response`-message is no longer raised.
=> BUG: Use async/await in api/saveUserUuid

models/User.js, pages/api/auth/[...nextauth].js
Again circling back to #32.
Previous fix was unable to fetch uuid values from `users`-table.
This fix comes from thread [https://github.com/nextauthjs/next-auth/issues/710](https://github.com/nextauthjs/next-auth/issues/710). Extending the TypeORM User-model resulted in issues in relation naming on production builds. This fix constructs the model from scratch.
Tested on both dev environment and production builds (`next build` -> `next start`) and works well.
=> Custom model fix

components/quiz.js, components/quizTest.js, pages/api/getLocationsTest.js, styles/global.css
Fixes #65
Implements country name overlay in both the actual mapping game, and the testing exercise (testing data was missing country data, which has been added).
Until we have a better design, this may do:
=> BLD: add country name overlay to map

components/intro.js, pages/mapping.js
Fixes #66:
- `intro` page checks if either the user is logged in (session exists) or there is a cookie for this user. If so, checks if the existing user has mapped any schools already. If there is mapping activity the `Start Mapping` button on the intro page will link to `/mapping` for the user to map more schools (thereby bypassing `/tips` and `/start-test`), otherwise `Start Mapping` button links to `/tips`
- Removes `<div>` from intro page that contained the text "Want to know what a school looks like on a map? View school mapping tips"
- Adds placeholder FAQ for **What does a school look like on a map?** We can go ahead and merge this PR, and when we receive the revised text for this FAQ, we can adjust it on a separate PR.
Revised intro page:
=> BLD: inserted tips in flow

components/countryNameLabel.js, components/intro.js, components/quiz.js, components/quizTest.js, components/result.js, components/resultTest.js, styles/global.css
Themes the country label overlay introduced in #73, as depicted below, both in the test and the actual mapping game.
Isolated the label to its own component for easier reusability.
=> BLD: theme for country label overlay

components/result.js
Previously, when a user mapped all schools, the text informing her/him that s/he had mapped all schools was fairly small.
Replaced the second fact on the result screen with the congratulatory message, as depicted below:
=> BLD: adjusted result text

pages/api/getCampaignStats/[campaign].js, pages/campaign/[campaign].js
Fixes #72
Adds dynamically-generated page to provide an overview for ongoing campaigns. Currently, one needs to hardcode dictionary with the campaign details at `pages/campaign/[campaign].js`, like so:
```
const campaigns = {
"mapbox": {
name: 'Mapbox',
users: 1000,
schools: 1000,
taggings: 10000,
}
}
```
which then results in a display as follows:
ToDo:
- build functionality to filter by campaign in API endpoint, will defer to another PR.
=> Add Campaign Overview Page

pages/api/getCampaignStats/[campaign].js, pages/campaign/[campaign].js
* Removed `schools` from campaign page
* Changed wording to `Locations Mapped`, realized that *Total number of locations mapped* was unnecessarily verbose
* Refactored the handling of the `404` because the way it was before, it momentarily showed a 404 until the page was properly loading. Instead, it currently doesn't display anything until it gets the **campaign** variable from the query, at which point it either displays the page or redirects to a 404
=> BLD: refactor Campaign page

components/headerComponent.js, db/dbOps.js, models/User.js, pages/api/getCampaignStats/[campaign].js, pages/api/getUserTeam/[uuid].js, pages/api/updateUserTeam.js, pages/campaign/[campaign].js, pages/profile.js, public/icons/greentick.svg, styles/global.css
This PR adds the functionality for the users to add themselves to a team in their profile page:
* a one-field form is added to the `/profile` page with hardcoded values for a select field type, where the user can choose a team
* the above field updates the `users` table in the DB via a new API endpoint (a second API endpoint was created to read the value from that field for a given user)
* a nifty animation is added to visually notify the user that the value has been updated (which then fades out), all using only CSS
* the signin flow is altered with the specification of a callbackUrl so that users are redirected to `/profile` upon signing in. For new users, it will be thus evident to add themselves to a team
* the dynamic `/campaign/[campaign]` page is modified to use the value of the …
=> BLD: ability to set Teams

components/headerComponent.js, pages/campaign/[campaign].js, pages/profile.js
A major usability bug was introduced in #85 where a the `signin` call was passed directly to `onClick` instead of a reference to it. This has been fixed in bc2e9f7
Additionally an internal campaign for UNICEF has been set up in 806ff4a
=> BUG: fix signin call

pages/api/summaryUsers.js, pages/campaign/[campaign].js
- Add leaderboard in `/campaign/[campaign]` page, which displays a table of users and their count of locations mapped. If no users have mapped any location, the table displays an "empty" message.
- Refactor `pages/api/summaryUsers.js` used previously in `/summary` page to accept optional parameters to display usernames instead of user_ids and filter by campaign.
See screenshots:
=> BLD: leaderboard in campaign page

components/result.js
On the results page, changed "You just mapped 10 schools" to "You just mapped 10 locations" for accuracy.
=> Changes "schools" --> "locations"

components/progressBar.js, components/quiz.js
In response to #93, I have increased padding:
* Above the 'Next' button while user responses are being shown after the user clicks on a response
* To the left and right of the progress bars to provide a tiny bit more room between the bar and the text
I have added a line break before the 'Next' button and some additional whitespace around the progress bar in the ProgressBar element.
=> Increased quiz element padding

package-lock.json, package.json
Follow up to #100, since version 6 of Husky does not install the git hooks automatically, but version 4 does. This is documented [elsewhere](https://stackoverflow.com/questions/50048717/lint-staged-not-running-on-precommit).
Cc: @Rolikasi
=> MAINT: downgraded husky

.github/workflows/main.yml
Fixes: #96 
Created a new main.yml file to describe the workflow for checking linting and prettier.
@lacabra please review.
=> Added Github actions to check Linting and Prettier 

pages/mapping.js
Fixes unicef/projectconnect-app#11
The bug was caused by loading the locations to be mapped before the `session` had finished loading, thus the user was not properly identified, and locations were instead selected based on another identifier (that is randomly every time). The fix waits for the session to be loaded, and then queries the API with the right identifier associated to the logged in user, thereby resulting in the expected behavior.
=> BUG: fix selection of locations remaining

pages/campaign/[campaign].js
Fixes bug that caused race condition in the display of campaign stats, where either no data is shown at all (screenshot below), data is shown momentarily, or only partial data is displayed. I believe the race condition is caused by the async call to setCampaign, where currently fetch data is not dependent on that state variable to be set, but its value from router.query is passed directly to fetch data.
=> BUG: fix race condition in display campaigns

components/quizTest.js
There was a slight visibility issue in the "Yes" and "No" buttons in the quiz section. The comparison is shown through screenshots below:
**BEFORE**
We notice in the above two cases that the Yes and No labels are not properly visible due to the background colour added. 
**AFTER**
The issue has been fixed by changing the class to make the colour of the labels white on answering.
=> Fixed button styling issue on answer
